# config.yaml

# Directories
DATA_DIR: "data"
FEATURES_DIR: "features"
MODELS_DIR: "../src/models"
OUTPUT_DIR: "output"
LOG_DIR: "logs"

# VGG hyperparameters
RANDOM_SEED: 42
BATCH_SIZE: 32
NUM_EPOCHS: 50
LEARNING_RATE: 0.001
LR_PATIENCE: 5
WEIGHT_DECAY: 0.00001
DROPOUT_RATE: 0.3

# Cross-validation Params
N_FOLDS: 5
CV_SHUFFLE: true
CV_STRATIFY: true

CLASS_NAMES: ["peni", "aspfum", "aspfla", "clado", "fus"]

# LightGBM-specific
LGB_NUM_BOOST_ROUND: 1000
LGB_EARLY_STOPPING: 50
LGB_LEARNING_RATE: 0.05
LGB_MAX_DEPTH: 7

DEVICE: "cuda"
INFER_BATCH_SIZE: 64
